server:
  port: 8090
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: sru_lib_management
  datasource:
    url: jdbc:mysql://${db_host:localhost}:${db_port:3306}/${db_name:sru_library}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
