server:
  port: 8090
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: sru_lib_management
  datasource:
    url: jdbc:mysql://localhost:3306/{database name}
    username: { username }
    password: { password }
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
