server:
  port: 8090
spring:
  main:
    allow-circular-references: true
  application:
    name: sru_lib_management
  datasource:
    url: jdbc:mysql://localhost:3306/sru_library
    username: root
    password: viwath@261102
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
